### ISSUE TITLE
mozlog-formatted `Fields` can't be nested objects.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla-services/Dockerflow#19]
According to the pipeline team, we aren't able to nest object literals within the `Fields` object; just "values" and arrays. [This documentation](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md#fields-property) is wrong. See [this mana article](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=42895640) for the full schema.

**Comment by mostlygeek** [comment]
Fixed in #22
