### ISSUE TITLE
Convert to CircleCI 2.0

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/Dockerflow#32]
The 1.0 style configuration still used in this sample is supposedly retiring this August

https://circleci.com/blog/sunsetting-1-0/

**Comment by mostlygeek** [comment]
Yes this should be high priority.

**Comment by milescrabill** [comment]
I made a similar baseline example a few months ago when CircleCI 2.0 was new. See here: https://github.com/mozilla-services/ci-testground.

**Comment by mostlygeek** [comment]
Closed in #35
