### ISSUE TITLE
What should we return if /app/version.json is missing?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/Dockerflow#47]
- 500 ?
- Empty body?

**Comment by sciurus** [comment]
Maybe a 500 response wit a json-encoded error message that the version info was missing?

**Comment by leplatrem** [comment]
There should also be some logging somewhere to raise attention :)

**Comment by sciurus** [comment]
Seems reasonable to send anything contributing to a 5xx error to sentry, which there's an open issue for at mozilla/classify-client/issues/13
