### ISSUE TITLE
Using wellknown for health checks

### ISSUE THREAD

**Issue by moltar** [mozilla-services/Dockerflow#52]
Why not use `.wellknown` name space for health checks?

https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sciurus** [comment]
We have a large amount of applications and infrastructure that have implemented the paths described here, so we do not intend to change them.
